# Example 4.6

## simulate data from model with correlated
## errors (AR-(1) process with rho = 0.9)

```{r}
library(lmtest)
set.seed(1)

n <- 100
u <- rnorm(n, sd=0.5)
eps <- numeric(n)
eps[1] <- u[1]
for(i in 2:n){
  eps[i] <- 0.9*eps[i-1] + u[i]
}
x <- rnorm(n)
y <- -1 + 2*x + eps

fit <- lm(y~x)
write.csv(cbind(x,y), "data/7a.csv", row.names=FALSE)
```
```{r}
png(file="7a_1.png",width=600, height=350)
par(mfrow=c(1,2))
plot(x, y, col = "darkblue",
     main = "Errors with pos. autocor.: data and fit")
abline(fit, col = "red")

plot(1:n, fit$residuals, col = "darkblue",
     main = "Errors with pos. autocor.: residuals over time")
abline(h=0, col = "red")
dev.off()
```
```{r}
png(file="7a_2.png",width=600, height=350)
acf(fit$residuals,
    main = "empirical autocorrelation function",
    xlim = c(0, 20))

pacf(fit$residuals,
     main = "empirical partial autocorrelation function",
     xlim = c(0, 20)) ## no value plotted at 0
  ## horizontal dashed lines correspond to confidence intervals
  ## (presumedly 95%)
dev.off()
```
# Durbin-Watson test
```{r}
dwtest(fit)
```
