# Example 4.1


## read data
```{r}
library(foreign)
rent99 <- read.dta(file="data/rent99.dta")
write.csv(rent99, "r/07a_homosk_rent/rent.csv", row.names=FALSE)
```

## model
```{r}
fit <- lm(rent ~ area + poly(yearc,3), data = rent99)
summary(fit)

png(file="r/07a_homosk_rent/1.png",width=600, height=350)
par(mfrow=c(2,2))
plot(fit)
  ## will discuss all four plots
  ## for now, focus on the first one
dev.off()


## Tukey-Anscombe plot

png(file="r/07a_homosk_rent/2.png",width=600, height=350)
par(mfrow=c(1,1))
plot(fit, which=1)
dev.off()
  ## standardized or studentized residuals
  ## are more appropriate
  ## to assess homoscedasticity
  ## but Tukey-Anscombe plot also appropriate
  ## for zero-conditional mean assumption
  ## and easily interpretable
  ## typically, will also see strong deviations
  ## from homoscedasticity here

## plot estimated curves including partial residuals
pred <- predict(fit, type="terms")
resid <- residuals(fit, type="partial")
png(file="r/07a_homosk_rent/3.png",width=600, height=350)
plot(rent99$yearc, resid[,2], ylab="effect of year of construction",
     xlab="year of construction",
     main="effect year of construction incl. partial residuals")
help <- data.frame(yearc=rent99$yearc, fyear = pred[,2])
o <- order(help$yearc)
lines(help[o,1], help[o,2])
dev.off()
  ## effect seems slightly nonlinear

png(file="r/07a_homosk_rent/4.png",width=600, height=350)
plot(rent99$area, resid[,1], ylab="effect of area", xlab="area in sqm",
     main="effect area incl. partial residuals")
help <- data.frame(area=rent99$area, farea = pred[,1])
o <- order(help$area)
lines(help[o,1], help[o,2])
dev.off()
  ## effect seems linear

## Compute studentized residuals
rs <- rstudent(fit)

## Compute predicted values
pred <- predict(fit)

## Plot studentized residuals
png(file="r/07a_homosk_rent/5.png",width=600, height=350)
plot(pred, rs, ylab="studentized residuals",
     xlab="estimated rent",
     main="studentized residuals versus estimated rent",
     ylim=c(-5,7))
abline(h=0, col = "red")
dev.off()
  ## clear evidence of heteroscedasticity

png(file="r/07a_homosk_rent/6.png",width=600, height=350)
plot(rent99$area, rs, ylab="studentized residuals",
     xlab="area in sqm",
     main="studentized residuals versus area",
     ylim=c(-5,7))
abline(h=0, col = "red")
dev.off()

  ## clear evidence of heteroscedasticity
png(file="r/07a_homosk_rent/7.png",width=600, height=350)
plot(rent99$yearc, rs, ylab="studentized residuals",
     xlab="year of construction",
     main="studentized residuals versus year of construction",
     ylim=c(-5,7))
abline(h=0, col = "red")
dev.off()
  ## somewhat weaker evidence of heteroscedasticity

## scale location plot
png(file="r/07a_homosk_rent/8.png",width=600, height=350)
plot(fit, which=3)
dev.off()
  ## clear evidence of heteroscedasticity
```
